export const DEFAULT_ROLES = [
  {
    name: 'owner',
    description: 'Full access to the project',
    permissions: [
      'projects:read',
      'projects:update',
      'projects:delete',
      'members:read',
      'members:create',
      'members:delete',
      'users:read',
      'users:update',
      'records:read',
      'records:create',
      'records:update',
      'records:delete',
      'api_keys:read',
      'api_keys:create',
      'api_keys:delete',
    ],
  },
  {
    name: 'admin',
    description:
      'Manage the project, members and records, but cannot delete the project',
    permissions: [
      'projects:read',
      'projects:update',
      'members:read',
      'members:create',
      'members:delete',
      'users:read',
      'users:update',
      'records:read',
      'records:create',
      'records:update',
      'records:delete',
      'api_keys:read',
      'api_keys:create',
      'api_keys:delete',
    ],
  },
  {
    name: 'developer',
    description: 'Read the project and manage records',
    permissions: [
      'projects:read',
      'members:read',
      'records:read',
      'records:create',
      'records:update',
      'records:delete',
      'api_keys:read',
    ],
  },
  {
    name: 'viewer',
    description: 'Read-only access',
    permissions: ['projects:read', 'members:read', 'records:read'],
  },
];
